### ISSUE TITLE
kinesis?

### ISSUE THREAD

**Issue by justinmchase** [Medium/local-dynamo#43]
Is there anyway to hook up a kinesis stream to dynamo local that you know of? Are there any events coming out of it that I could use to redirect to a stream possibly?

**Comment by xiao** [comment]
@justinmchase, I don't think DynamoDB Local support DynamoDB Streams. Recommend you to raise this as a question to the AWS Support team. `local-dynamo` is just a Node.js wrapper around DynamoDB Local's Java process.

**Comment by justinmchase** [comment]
I've since found out that it doe's support it, you just have to use the app endpoints to create the streams before you use them.
